version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synapse-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=http://qdrant:6333
    networks:
      - default
    depends_on:
      - redis
      - qdrant
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - default
    command: redis-server --appendonly yes
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - default
    depends_on:
      - redis
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - default
    environment:
      - QDRANT_ALLOW_RECOVERY=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  redis_data:
  qdrant_data:

networks:
  default:
    name: synapse_network
    external: true 