apiVersion: 1

groups:
  - name: SynapseAlerts
    rules:
      # Performance Alerts
      - alert: HighLatency
        expr: rate(llm_response_time_seconds_sum[5m]) / rate(llm_response_time_seconds_count[5m]) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alta latência nas respostas LLM"
          description: "Tempo médio de resposta > 2s nos últimos 5 minutos"

      # Cost Alerts
      - alert: HighTokenUsage
        expr: sum(increase(llm_token_usage_total[1h])) > 100000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alto consumo de tokens"
          description: "Uso de tokens excedeu 100k na última hora"

      # User Experience Alerts
      - alert: HighErrorRate
        expr: sum(rate(errors_total[5m])) / sum(rate(llm_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Taxa de erro elevada"
          description: "Taxa de erro > 5% nos últimos 5 minutos" 