/** @generated-by-lovable - DO NOT EDIT */
import React from 'react';

export function TestComponent() {
  return (
    <div>
      <h1>Test Component</h1>
      <p>This is a test component generated by Lovable</p>
    </div>
  );
}
/** @end-lovable */ 